import type { MysteryCase } from './types';

export const cases: MysteryCase[] = [
  {
    id: 'glasshouse-lantern',
    name: 'The Glasshouse Lantern',
    premise: 'The moonflower lantern vanished minutes before the garden fundraiser opened.',
    missing: 'A brass lantern containing the garden’s first moonflower cutting',
    paid: false,
    suspects: [
      { id: 'mira', name: 'Mira Vale', role: 'Garden curator', note: 'Locked the display at 7:40.' },
      { id: 'ben', name: 'Ben Alder', role: 'Head gardener', note: 'Watered the west beds until 7:55.' },
      { id: 'celia', name: 'Celia Finch', role: 'Botanical illustrator', note: 'Sketched beside the display.' },
      { id: 'theo', name: 'Theo Reed', role: 'Event caterer', note: 'Set out tea in the south aisle.' },
    ],
    clues: [
      [
        { title: 'Pressed leaflet', text: 'A fresh fern leaflet lies inside the empty display.', detail: 'Its underside carries a thin stripe of cobalt chalk.', specimen: 'leaf' },
        { title: 'Display lock', text: 'The lock has no scratches and still turns cleanly.', detail: 'Only Mira and Ben carry display keys.', specimen: 'key' },
        { title: 'Sketching stool', text: 'Celia’s stool faces the display from two steps away.', detail: 'A blue chalk pencil rests beneath it.', specimen: 'paper' },
        { title: 'Tea count', text: 'Theo prepared five cups, but only four were used.', detail: 'One cold cup sits near the west door.', specimen: 'cup' },
        { title: 'Watering marks', text: 'A damp wheel track ends at the west beds.', detail: 'The track never reaches the display.', specimen: 'soil' },
        { title: 'Gallery clock', text: 'The clock stopped at 7:48 after a brief power cut.', detail: 'The emergency lamps came on at once.', specimen: 'clock' },
        { title: 'Floor print', text: 'One narrow shoe print crosses a spilled patch of soil.', detail: 'It points away from the display toward the studio door.', specimen: 'shoe' },
        { title: 'Vent pane', text: 'The display’s rear vent stands open by two fingers.', detail: 'A slender arm could reach the inner latch.', specimen: 'glass' },
      ],
      [
        { title: 'Fern source', text: 'The leaflet matches the fern beside Celia’s easel.', detail: 'That plant was dry when the other beds were watered.', specimen: 'leaf' },
        { title: 'Key record', text: 'Mira signed both display keys back into the cabinet at 7:42.', detail: 'The cabinet seal was unbroken at 8:00.', specimen: 'key' },
        { title: 'Missing sketch', text: 'Celia says she drew the east arch during the power cut.', detail: 'Her pad contains no arch sketch and one page is missing.', specimen: 'paper' },
        { title: 'Tea receipt', text: 'Theo’s kettle logged its final boil at 7:49.', detail: 'The south aisle outlet powered the kettle during the cut.', specimen: 'cup' },
        { title: 'Boot width', text: 'Ben’s boots are wider than the narrow soil print.', detail: 'Wet clay on his soles matches the west beds.', specimen: 'shoe' },
        { title: 'Clock reflection', text: 'A visitor’s photo shows the display at 7:51.', detail: 'The lantern is still visible behind the glass.', specimen: 'clock' },
        { title: 'Studio route', text: 'The narrow print ends beside a canvas tote in the studio.', detail: 'The tote is clean outside but dusty inside.', specimen: 'shoe' },
        { title: 'Vent latch', text: 'A line of cobalt dust marks the inside latch.', detail: 'The display key was not needed to open it.', specimen: 'glass' },
      ],
      [
        { title: 'Torn tracing paper', text: 'A tracing-paper triangle is caught under the vent.', detail: 'Its deckled edge points down and left.', specimen: 'paper' },
        { title: 'Matching page', text: 'Celia’s pad has a missing corner with the same fibres.', detail: 'The tracing-paper triangle fits the gap exactly.', specimen: 'paper' },
        { title: 'Chalk transfer', text: 'Cobalt chalk marks the vent, fern, and Celia’s pad.', detail: 'The other suspects carry no blue drawing material.', specimen: 'leaf' },
        { title: 'Lantern warmth', text: 'The recovered tote feels warm beside the cold tea cup.', detail: 'The lantern had been hidden inside moments earlier.', specimen: 'cup' },
        { title: 'Clean wheel', text: 'Ben’s barrow holds only soil and watering tools.', detail: 'Its track matches every damp mark in the aisle.', specimen: 'soil' },
        { title: 'Final minute', text: 'The lantern vanished between 7:51 and 7:54.', detail: 'Mira was greeting donors at the glasshouse entrance.', specimen: 'clock' },
        { title: 'Shoe comparison', text: 'Celia’s narrow shoes match the print length and tread.', detail: 'Theo’s shoes have a square heel that is absent.', specimen: 'shoe' },
        { title: 'Folded label', text: 'The tote contains the lantern’s folded specimen label.', detail: 'Graphite shading matches Celia’s unfinished study.', specimen: 'glass' },
      ],
    ],
    answer: 'celia',
    reveal: 'Celia reached through the rear vent with a rolled tracing page, lifted the latch, and hid the lantern in her canvas tote. The matching paper tear, cobalt transfers, and narrow shoe print connect the whole route. She wanted one private night to finish her moonflower study before the cutting left the garden.',
    replayNote: 'Start a new room to reshuffle notebook numbers across the same evidence trail.',
  },
  {
    id: 'orchid-ledger',
    name: 'The Orchid Ledger',
    premise: 'A hand-drawn pollination ledger disappeared during the conservatory supper.',
    missing: 'The garden’s only record of a twelve-year orchid project',
    paid: true,
    suspects: [
      { id: 'asha', name: 'Asha Moss', role: 'Seed librarian', note: 'Catalogued new packets in the north room.' },
      { id: 'jonah', name: 'Jonah Elm', role: 'Glasshouse keeper', note: 'Checked the misting pipes.' },
      { id: 'liv', name: 'Liv Rowan', role: 'Event photographer', note: 'Photographed the supper tables.' },
      { id: 'omar', name: 'Omar Wren', role: 'Visiting researcher', note: 'Compared flowers near the archive.' },
    ],
    clues: [
      [
        { title: 'Empty drawer', text: 'The ledger drawer is open without damage.', detail: 'A loop of green thread rests in the runner.', specimen: 'paper' },
        { title: 'Archive key', text: 'Asha’s archive key stayed on a signed cord.', detail: 'The knot has not been retied.', specimen: 'key' },
        { title: 'Camera strap', text: 'Liv’s camera strap uses black woven cord.', detail: 'No green fibres cling to it.', specimen: 'glass' },
        { title: 'Pipe check', text: 'Jonah logged low pressure in bay three.', detail: 'Drops from his coat lead only to the pump.', specimen: 'soil' },
        { title: 'Sample wrap', text: 'Omar carries samples tied with green linen thread.', detail: 'One bundle is missing its tie.', specimen: 'leaf' },
        { title: 'Supper time', text: 'The main toast began at 8:12.', detail: 'Every guest faced the west table.', specimen: 'clock' },
        { title: 'Dust line', text: 'Fine archive dust crosses one polished shoe.', detail: 'The print points toward the reading bench.', specimen: 'shoe' },
        { title: 'Water glass', text: 'A half-full glass sits on the reading bench.', detail: 'A ring of dust surrounds its clean base.', specimen: 'cup' },
      ],
      [
        { title: 'Thread twist', text: 'The drawer fibre twists clockwise in two strands.', detail: 'Omar’s sample thread has the same weave.', specimen: 'paper' },
        { title: 'Spare key', text: 'The reading bench hides an old drawer key.', detail: 'Any visitor seated there could see it.', specimen: 'key' },
        { title: 'Photo sequence', text: 'Liv’s photos cover the room from 8:09 to 8:15.', detail: 'Omar is absent from the frame at 8:12.', specimen: 'glass' },
        { title: 'Misting alarm', text: 'The pipe alarm sounded at 8:11.', detail: 'Jonah appears on the pump camera until 8:14.', specimen: 'soil' },
        { title: 'Research note', text: 'Omar says he returned his samples before the toast.', detail: 'His signed return time reads 8:18.', specimen: 'leaf' },
        { title: 'Stopped timer', text: 'A pocket timer under the bench shows six minutes.', detail: 'It was started at the 8:12 toast.', specimen: 'clock' },
        { title: 'Shoe dust', text: 'Omar’s polished shoe is wiped on top.', detail: 'Archive dust remains in the sole groove.', specimen: 'shoe' },
        { title: 'Clean circle', text: 'The glass protected a circle from settling dust.', detail: 'It was placed before the drawer opened.', specimen: 'cup' },
      ],
      [
        { title: 'Snagged thread', text: 'The green loop holds a tiny paper fibre.', detail: 'Its edge matches Omar’s torn sample wrap.', specimen: 'paper' },
        { title: 'Key print', text: 'The spare key carries one fresh thumbprint in graphite.', detail: 'Omar used graphite while comparing flower diagrams.', specimen: 'key' },
        { title: 'Reflected bench', text: 'Liv’s 8:12 photo reflects the reading bench in a vase.', detail: 'Omar’s green-thread bundle is visible there.', specimen: 'glass' },
        { title: 'Dry route', text: 'No water drops cross from the pump to the archive.', detail: 'Jonah did not take the ledger route.', specimen: 'soil' },
        { title: 'Folded ledger', text: 'The ledger fits inside an empty sample portfolio.', detail: 'Omar’s portfolio has fresh square pressure marks.', specimen: 'leaf' },
        { title: 'Six-minute gap', text: 'The timer stopped at 8:18 beside Omar’s signed return.', detail: 'His unexplained absence lasted exactly six minutes.', specimen: 'clock' },
        { title: 'Matching sole', text: 'Omar’s sole groove matches the reading-bench print.', detail: 'The other shoes use different tread patterns.', specimen: 'shoe' },
        { title: 'Water ring', text: 'The dust ring proves the glass was staged early.', detail: 'It does not support Omar’s claim that he read there later.', specimen: 'cup' },
      ],
    ],
    answer: 'omar',
    reveal: 'Omar used the spare key during the toast and slipped the ledger into his sample portfolio. The matching green thread, graphite thumbprint, reflected bundle, and dusty shoe establish the route. He planned to copy unpublished observations before returning the ledger.',
    replayNote: 'Create another room to assign the evidence to different notebooks.',
  },
];

export const caseById = (id: string) => cases.find((item) => item.id === id) ?? cases[0];
